export const acronymData = {
        A: { names: {
            AA:	"Adult Anonymous",
            ABT: "Account-Based Ticketing",
            ABTI: "Account Based Ticketing Integration",
            AG: "Automatic Gate",
            AFC: "Automated Fare Collection",
            AI:	"Artificial Intelligence",
            AMTP: "Adult Monthly Fare Collection System",
            API: "Application Programming Interface",
            AR:	"Audit Register",
            ASK: "Assisted Service Kiosk",
            ATU: "Auto Top Up",
            AVC: "Add Value Counter",
            AVM	: "Add Value Machine",
            AVMS: "Automatic Vehicle Management System",
            AVR: "Account Verification Request",
            AVSO: "Add Value Scheme Owner"
        },
        open: false
    },
    B: { names: {
            BA	:	"	Bank Acquirer	",
            BA	:	"	Business Analyst	",
            BCM	:	"	Bus Contracting Model	",
            BCO	:	"	Bedok Campus Office	",
            BCP	:	"	Bus Concession Pass	",
            BCV	:	"	Bus Card Validator	",
            BDRL:	"	Bad Debt Risk Liability	",
            BEP	:	"	Bus Entry Processor	",
            BEXP:	"	Bus Entry-Exit Processor	",
            BEV	:	"	Bus Entry Validator	",
            BFC	:	"	Bus Fare Console	",
            BHS	:	"	Bulk Host System	",
            BIN	:	"	Bank Indentification Number	",
            BIS	:	"		",
            BL	:	"	Blacklist or Blocklist	",
            BLS	:	"	Bus Location Service	",
            BLOB	:	"	Binary Large Object	",
            BNCC	:	"	Bus Network Central Computer	",
            BO  :	"	Bus Operator	",
            BOCC:	"	Bus Operator Central Computer	",
            BOLC:	"	Bus On-Line Connectivity	",
            BOS	:	"	Back Office System	",
            BOSE:	"	Bus Operator Standard Edition	",
            "BO-BCM":	"	Bus Operator - Bus Contracting Model	",
            "BO-NBCM":	"	Bus Operator - Non-Bus Contracing Model	",
            BPLRT	:	"	Bukit Panjang Light Rapid Transit	",
            BPLS	:	"	Bukit Panjang LRT Service Provider	",
            BR	:	"	Business Requirement	",
            BRTC:	"	Business Rules for Thin Client	",
            BS	:	"	Build Standard	",
            BSEP:	"	Bus Service Enhancement Programme	",
            BSI	:	"	British Standards Institute	",
            BTP	:	"	Bus Ticketing Project	",
            BTS	:	"	Bus Ticketing System	",
            BXP	:	"	Bus Exit Processor	",
            BXV	:	"	Bus Exit Validator	",            
        },
        open: false
    },
    C: { names: {
            CA	:	"	Configuration Audit	",
            CAN	:	"	Card Application Number	",
            CBN	:	"	Communication Backbone Network	",
            CBD	:	"	Central Business District	",
            CBT	:	"	Card-Based Ticketing	",
            CC	:	"	Central Computer	",
            CC	:	"	Customer Claim	",
            CCB	:	"	Change Control Baord	",
            CCL	:	"	Circle Line	",
            CCLS:	"	Circle Line Service Provider	",
            CCRO:	"	Concession Card Replacement Office	",
            CCRS:	"	Centralised Collections and Refunds System	",
            CCTC:	"	CePAS Compliance Test Center	",
            "CDM @ GUI"	:	"	Manager Graphic User Interface (Parameter)	",
            CDMS:	"	Central Device Management System	",
            cEMV:	"	Contactless Europay, Mastercard and VISA	",
            CePAS:	"	Specification for Contactless e-Purse Application	",
            CFC	:	"	Call for Collaboration	",
            CFMS	:	"	Central Fleet Management System	",
            CII	:	"	Critical Information Infrastructure	",
            "CIP/CPP"	:	"	Card Initialisation Processor / Card Personalisation Processor	",
            CM	:	"	Configuration Management	",
            CMP	:	"	Configuration Management Plan	",
            CMCC:	"	Card Manager Central Computer	",
            CMMI:	"	Capability Maturity Model Integration	",
            CMS	:	"	Customer Management System	",
            CMSE	:	"	Card Manager Standard Edition	",
            COTS	:	"	Commercial Off the Shelf	",
            CPA	:	"	Card Proceeds Account	",
            CPP	:	"	Card Personalisation Processor	",
            CR	:	"	Credit	",
            CRO	:	"	Card Replacement Office	",
            CSA	:	"	Configuration Status Accounting	",
            CSC	:	"	Contactless Smart Card	",
            CSCI	:	"	Computer Software Configuration Item	",
            "CSC R/Wa"	:	"	CSC Reader-Writera	",
            "CSC R/Wb"	:	"	CSC Reader-Writerb	",
            CSM	:	"	Customer Sales Machine	",
            CSRV:	"	Card Services	",
            "CT-AA"	:	"	CePAS Token - Adult Anonymous	",
            CTC	:	"	CePAS Token Card	",
            CTRU	:	"	Contactless Smart Card (CSC) Transit Reader Unit	",
            CTS	:	"	CePAS Tokenisation Server	",
            CUP	:	"	China Union Pay	",
        },
        open: false
    },
    D: { names: {
            DAGM:	"	Design Architecture Group Meeting	",
            DAGW:	"	Depot AFC Gateway	",
            DAR	:	"	Design Acceptance Review	",
            DB	:	"	Database	",
            DBA	:	"	Database Administrator	",
            DBTF:	"	Distance Based Through Fares	",
            DC	:	"	Data Center	",
            DCO	:	"	Data Center Operator	",
            DCR	:	"	DCC Control Room	",
            DCS	:	"	Depot Computer System	",
            DES	:	"	Data Encryption Standard	",
            DF	:	"	Distance Fares	",
            DHCP	:	"	Dynamic Host Certification Protocol	",
            DIT	:	"	Development Integration Test	",
            DL	:	"	Direct Line	",
            DMCC:	"	Device Manager Central Controller	",
            "DMC GUI":	"	Device Manager Control Graphic User Interface	",
            DMS	:	"	Data Management System	",
            DMSC:	"	Device Manager Site Computer	",
            DPAN:	"	Device Primary Account Number	",
            DR	:	"	Disaster Recovery	",
            DSS	:	"	Decision Support System	",
            DTL	:	"	Downtown Line	",
            DTLS:	"	Downtown Line Service Provider	",
        },
        open: false
    },
    E: { names: {
            ECU	:	"	Electic Control Unit	",
            EFT	:	"	Electronic Funds Transfer	",
            EI	:	"	External interface	",
            EIFS:	"	Enhanced Integrated Fare System	",
            EMC	:	"	Electro-Magnetic Compatibility	",
            EMM	:	"	Enterprise Mobility Management	",
            EMV	:	"	Europay, MasterCard and Visa	",
            EOD	:	"	End of Day	",
            EOL	:	"	End-of-Life	",
            EP	:	"	Employee Pass	",
            EPSC:	"	E-Payment Steering Committee	",
            ePD	:	"	e-Payment Device	",
            ePIC:	"		",
            EPS	:	"	Emergency Power Supply	",
            ERP	:	"	Electronic Road Pricing	",
            ESB	:	"	Enterprise Service Bus	",
            eSCC:	"	ePayment Standards Compliance Centre	",
            ESKMS:	"	Enhanced Security Key management System	",
            ETL	:	"	Extract, Transform, Load	",
            EVT	:	"	Event or Event Notifications	",
            EXMS:	"	Entry-Exit Monitoring System	",
            EZCM:	"	EZLink Card Manager	",
            EZL	:	"	EZ-Link	",
            EZSO:	"	EZLink Add Value Scheme Owner	"
        },
        open: false
    },
    F: { names: {
            FASTER:	"	Fusion Analytics for Public Transport Emergency	",
            FAT	:	"	First Article Test	",
            FCA :	"	Functional Configuration Audit	",
            FCMS:	"	Fare Computation Management System	",
            FDDI:	"	Fibre Distributed Data Interface	",
            FEP	:	"	Front End Processor	",
            FI	:	"	Fund Issuer	",
            FIN	:	"	Finance	",
            FLP	:	"	Fixed Location Processor	",
            FPAN:	"	Funding Primary Account Number	",
            FRE	:	"	Fare Revision Exercise	",
            FRL	:	"	First Ride Liability 	",
            FS	:	"	Fare System 	",
            FSBS:	"	Fare System - Bus and Systems Projects	",
            FSD	:	"	Fare System Department	",
            FSRS:	"	Fare System - Rail Projects and Support 	",
            FT	:	"	Functional Test	",
            FTN	:	"	Field Trial Notice	",
            FTP	:	"	File Transfer Protocol	",
            FTPS:	"	File Transfer Protocol Secure	",
        },
        open: false
    },
    G: { names: {
            GABO:	"	Go-Ahead Bus Operator	",
            GBD	:	"	Gali Batu Depot	",
            GBP	:	"	Global Back-end Parameters	",
            GCM	:	"	Gross Cost Model	",
            GFA	:	"	Good for Apportionment	",
            GFS	:	"	Good for Settlement	",
            GIRO:	"	General Interbank Recurring Order	",
            GPS	:	"	Global Positioning System	",
            GTM	:	"	General Ticketing Machine	",
            "GTM - BNA":	"	General Ticketing Machine - Bank Note Acceptor	",
            GUI	:	"	Graphical User Interface	",

        },
        open: false
    },
    H: { names: {
            HA	:	"	High Availability	",
            HCP	:	"	Hybrid Concession Pass	",
            HEP	:	"	Handheld Entry Processor	",
            HIT	:	"	Hardware Integration Test	",
            HPQC:	"	HP Quality Center	",
            HSM	:	"	Hardware Security Module	",
            HTTP:	"	Hypertext Transfer Protocol	",
            HTTPS:	"	Hypertext Transfer Protocol Secure	",
            HWCI:	"	Handware Configuration Items	",
        },
        open: false
    },
    I: { names: {
            IAA	:	"	Internal Approving Authority	",
            IALM	:	"	Integrated Application Lifecycle Management system	",
            IBOS	:	"	Integrated Bus Operation System	",
            ICS	:	"	Interchange Computer System	",
            IDFC	:	"	Integrated Drivers Fare Console	",
            IEC	:	"	International Electrotechnical Commission	",
            IEEE	:	"	Institute of Electrical & Electronics Engineers	",
            IFCC	:	"	Integrated Fare Central Computer	",
            IIB	:	"	IBM Integration Bus	",
            IIS	:	"	Integrated Initialisation System	",
            IMS	:	"	Inquiry Management System	",
            "I/O"	:	"	Input/Output	",
            IOCC	:	"	Integrated Operation Control Centre	",
            IP	:	"	Internet Protocol	",
            IPD	:	"	Inspection Device	",
            ISCS	:	"	Integrated Supervisory Control System	",
            ISIF	:	"	Integrated Security Access Module (SAM) Initialisation Facility	",
            ISO	:	"	International Organization for Standardisation	",
            ITB	:	"	Interface Terminal Box	",
            ITCAM	:	"	IBM Application Performance Tool	",
            ITC	:	"	Integrated Test and Comissioning	",
            ITCD	:	"	Information Technology Cyber security and Digital services	",
            ITFS	:	"	Integrated Ticketing & Fleet Management System	",
            IVRS	:	"	Integrated Voice Recording System	",
        },
        open: false
    }, 
    J: { names: {
        
        },
        open: false
    },
    K: { names: {
            KCD	:	"	Kim Chuan Depot	",
            KMF	:	"	Key Management Facility	",
            KPE	:	"		",
        },
        open: false
    },
    L: { names: {
            LAN	:	"	Local Area Network	",
            LB	:	"	Load Balancer	",
            LRT	:	"	Light Rapid Transit	",
            LTA	:	"	Land Transport Authority	",
            LTAB	:	"	LTA Bus Operator	",
            LV	:	"	Low Voltage	",
        },
        open: false
    },
    M: { names: {
            MAS	:	"	Monetary Authority of Singapore	",
            MASS:	"	Multiple Applciation Smartcard System	",
            MAC	:	"	Message Authenication Code	",
            MBO	:	"	Master Bus Operator	",
            MCBF:	"	Mean Cycle Between Failure	",
            MCC	:	"	Monitoring and Control Client	",
            MCS	:	"	Monitoring and Control System	",
            MCW	:	"	Monitoring and Control Workstation	",
            MD	:	"	Message Data	",
            MDCS:	"	Master Depot Computer System	",
            MDM	:	"	Mobile Device Management	",
            MID	:	"	Mobile Inspection Device	",
            MIT	:	"	Merchant Initiated Transaction	",
            MMS	:	"	Maintenance Management System	",
            MOD	:	"	Mobility On-Demand	",
            MOT	:	"	Ministry of Transport	",
            MQ	:	"	Message Queue	",
            MQTA:	"	Mobile Quantum Analyzer	",
            MQTT:	"	Message Queue Telemetry Transport	",
            MRT	:	"	Mass Rapid Transit	",
            MSI :   "",
            MSN	:	"	Message Sequence Number	",
            MTBF:	"	Mean Time Between Failure	",
            MTTR:	"	Mean Time To Repair	",
        },
        open: false
    },
    N: { names: {
            NC	:"	New Card	",
            NECM:"	NETS Card Manager	",
            NEL	:"	North-East Line	",
            NELS:"	NEL Service Provider	",
            NETS:"	Network of Electronic Transfer Singapore	",
            NFC:"	Near-Field Communication	",
            "NFC SIM":"	Near Field Communication Subscriber Identity Module	",
            "NFP or NETS FP":"	NETS Flashpay	",
            NGFA:"	Not Good For Apportionment	",
            NGFS:"	Not Good For Settlement	",
            NIPS:"	Network Intrusion Prevention System	",
            NMS	:"	Network Management System	",
            NOBE:"	New On-board Bus Equipment	",
            "Notice PSOA-N02":"		",
            "Notice PSOA-N03":"		",
            NRT	:"	Near Real Time	",
            NS	:"	Neutron Server	",
            NTA	:"	Non-Transit Application	",
            NTP	:"	Network Time Protocol	",
            NVA	:"	Network Virtual Appliance	",
        },
        open: false
    },
    O: { names: {
            OCC	:"	Operations Control Center	",
            OCS	:"	Operation Central Server	",
            OIC	:"	Overall In-Charge	",
            OLAP:"	Online Analytical Processing	",
            OLTP:"	Online Transaction Processing	",
            OOS	:"	Out of Service	",
            OPD	:"	On-board ePayment Device	",
            OS	:"	Operating System	",
            OTP	:"	One-Time Password	",
        },
        open: false
    },
    P: { names: {
            PAN	:"	Primary Account Number	",
            PBA	:"	Pool-Based Apportionment	",
            PBO	:"	Private Bus Operator	",
            "PCI DSS"	:"	Payment Card Industry Data Security Standard	",
            PDMS	:"	Parameter Distribution Management System	",
            PDT	:"	Parameter Description Table	",
            PDU	:"	Passenger Display Unit	",
            PG	:"	Payment Gateway	",
            PGIS	:"	Payment Gateway Interface Services	",
            "PG-CT"	:"	Payment Gateway - CePAS Token	",
            "PG-EMV"	:"	Payment Gateway - Europay, MasterCard and Visa	",
            "PGL LRT"	:"	Punggol Light Rapid Transit	",
            PGLS	:"	PGLRT Service Provider	",
            PID	:"	Passenger Information Display	",
            PIN	:"	Personal Identification Number	",
            PKE	:"	Purse Key Enhancement	",
            "PKE F1"	:"	Purse Key Enhancement Format 1	",
            "PKE F2"	:"	Purse Key Enhancement Format 2	",
            PLANET	:"	Planning for Land Transport Network	",
            PLC	:"	Programmable Logic Controller	",
            PLQ	:"	Paya Lebar Quarter	",
            POC	:"	Proof of Concept	",
            POSB	:"	Post Office Savings Bank	",
            PPL	:"	Posting Period Limit	",
            PRMS	:"	Parameter Services	",
            "PS(O)R"	:"	Payment Systems (Oversight) Regulations	",
            "PS(O)(E)R"	:"	Payment Systems (Oversight) (Exemption) Regulations	",
            "PS(O)(ESPSVF)O"	:"	Payment Systems (Oversight) (Exclusion of Single Purpose Stored Value Facilities) Order	",
            PSC	:"	Passenger Service Centre	",
            PSM	:"	Passenger Service Machine	",
            PTC	:"	Public Transport Council	",
            PTCA	:"	Public Transport Council Act	",
            PTO	:"	Public Transport Operator	",
            PTP	:"	Public Transport Promotion	",
            "PUB/SUB"	:"	Publish/Subscribe	",
            PWD	:"	Person with Disabilities	",
        },
        open: false
    },
    Q: { names: {
            QA	:"	Quality Assurance	",
            QB	:"	QB Pte Ltd	",
            QC	:"	Quality Check	",
            QMS	:"	Quality Management System	",
            QNX :"  ",
            QTA	:"	Quantum Analyzer	",
        },
        open: false
    },
    R: { names: {
            RAOM:"	Rail Asset, Operation and Maintenance	",
            RCA	:"	Root Cause Analysis	",
            RDM	:"	Requirement Development & Management	",
            RF	:"	Radio Frequency	",
            RFE	:"	Request for Enhancement	",
            RFU	:"	Reserved for Future Use	",
            RM	:"	Requirement Manager 	",
            RMB	:"	RFE Management Board	",
            RMF	:"	Ride Maximum Fare	",
            RNCC:"	Rail Network Central Computer	",
            RO	:"	Rail Operator	",
            ROCC:"	Rail Operator Central Computer	",
            ROEE:"	Rail Operator Extended Edition	",
            RSE :"  Rail/ Road Systems Engineering  ",	
            RTP	:"	Rail Ticketing Project	",
            RTS	:"	Rail Ticketing System	",
            RUP	:"	Rational Unified Process	",
            RV	:"	Remaining Value	",
        }, 
        open: false
    },
    S: { names: {
            SAA	:"	System Architecture and Assurance	",
            SAM	:"	Security Access Module	",
            SAM	:"	Supplier Agreement Management	",
            SAMM:"	Security Access Module Manager	",
            Sap	:"	Systems, Applications and Products	",
            SAT	:"	System Acceptance Test	",
            SAT	:"	Site Acceptance Test	",
            SBC	:"	Safe, better and more Cost-effective	",
            SBSN:"	SBST Service Provider Non-BCM	",
            SBST:"	Singapore Bus Service Transit	",
            "SBST-AVMS"	:"	SBST - Automated Vehicle Management System	",
            SC	:"	Station Computer	",
            SCA	:"	Smart Card Analyzer	",
            SCM	:"	Software Configuration Management	",
            SCFO:"	Station Computer Fail Over	",
            SCTC:"	Station Computer for Thin Client	",
            SD	:"	System Development	",
            SeP	:"	Symphony for ePayment	",
            SFTP:"	Secure File Transfer Protocol or SSH File Transfer Protocol	",
            SGD	:"	System-Generated Data	",
            SGN	:"	System-Generated Notification	",
            SIT	:"	System Intergration test	",
            SIRIUS:"	SIRIUS Card reader/writer unit	",
            SKGD:"	Sengkang LRT Service Provider	",
            "SKG LRT"	:"	Sengkang Light Rapid Transit	",
            SKMS:"	Security Key Management System	",
            SMRB:"	SMRT Bus Operator (Under BCM)	",
            SMRN:"	SMRT Service Provider Non-BCM	",
            SMRT:"	SMRT Service Provider	",
            SOD	:"	Start of Day	",
            SOP	:"	Standard Operating Procedure	",
            SOW	:"	Scope of Work	",
            SP	:"	Service Provider	",
            SPMS:"	Security Protection and Management System	",
            SS	:"	Shared Services	",
            ST	:"	Standard Ticket	",
            STAR:"	Settlement & Reporting Services	",
            STC	:"	Site Testing and Commisioning	",
            STE	:"	ST Electronics	",
            STEL:"	SMRT TEL Pte Ltd.	",
            STP	:"	Singapore Tourist Pass	",
            STYL:"	Sirius reader contractor	",
            SVF	:"	Stored Value Facility	",
            SWD	:"	System Wide Deployment	",
            SYSS:"	System Services	",
            SysArch: " System Architecture ",
        }, 
        open: false
    },
    T: { names: {                  
            "T&C":"	Terms and Conditions	",
            "T&C":"	Test and Commissioning	",
            TA	:"	Transit Acquirer	",
            TABA:"	Transit Acquirer System for Bank Card and Accounts	",
            TACC:"	Transit Acquirer Central Computer	",
            TAEE:"	Transit Acquirer Extended Edition	",
            TAPS:"	Trip Auto-Completion and Profiling System	",
            TCA	:"	Thin Client Application	",
            TCC	:"	Ticketing Contact Centre (Server and Client)	",
            TCP	:"	Train Concession Pass	",
            "TCP / TCP/IP"	:"	Transmission Control Protocol / Internet Protocol	",
            TCQ	:"	Tender Clarification Questions	",
            TDP	:"	Tourist Day Pass	",
            TEL	:"	Thomson-East Coast Line	",
            TELS:"	Thomson-East Coast Line Service Provider	",
            TET	:"	Tender Evaluation Team	",
            TFP	:"	Temporary Fire Permit	",
            TIS	:"	Transit Investigation Server	",
            TL	:"	Transit Link	",
            TLCM:"	Transit Link Card Manager	",
            TLLA:"	Transit Link Load Agent	",
            TLTA:"	Transit Link Transit Acquirer	",
            TLTO:"	Transit Link Ticketing Operator	",
            TLS	:"	Transport Security Layer	",
            TLSO:"	Transit Link Add Value Scheme Owner	",
            TLUS:"	Transit Link Unifed System	",
            TO	:"	Ticket Office	",
            TO	:"	Ticketing Operator	",
            TOCC:"	Ticketing Operator Central Computer	",
            TOIC:"	Ticketing Operator Interchange Computer	",
            TOPM:"	Transit Operator Performance Management	",
            TOR	:"	Term of Reference	",
            TQAR:"	Tenderer's Questions and Authority's Reply	",
            TSN	:"	Terminal Serial Number	",
            TSC	:"	Ticketing Service Centre	",
            TSJ	:"	Travel Smart Journey	",
            TSO	:"	Ticketing Services Operator	",
            TSP	:"	Ticketing Strategy and Projects	",
            TT	:"	Ticket Type	",
            TTBO:"	Tower Transit Bus Operator	",
            TUK	:"	Top Up Kiosk	",
            TUKA:"	Top Up Kiosk with Additional functions	",
            TUM	:"	Top Up Machine	",
            TVAS:"	Ticket Validity Adjustment Server	",
            TXNP:"	Transaction Processor	",
        },
        open: false
    },
    U: { names: {
            UAT	:"	User Acceptance Test	",
            UI	:"	User Interface	",
            UIMS:"	User Interface Management System	",
            UPS	:"	Uninterrupted Power Supply	",
        },
        open: false
    },
    V: { names: {
            VAPT:"	Vulnerability and Penetration Test	",
            VLAN:"	Virtual Local Area Network	",
            VLS	:"	Vehicle Location System	",
            VO	:"	Variation Order	",
            VSO	:"	Victoria Street Office	",
            VV	:"	Verification and Validation	",
        },
        open: false
    },
    W: { names: {
            WAN	:"	Wide Area Network	",
            WAPT:"	Web Application Penetration Test	",
            WBS	:"	Work Breakdown Structure	",
            WLAN:"	Wireless Local Area Network	",
            WSH	:"	Workplace Safety and Health	",
            WTCS:"	Workfare Transport Concession Scheme	",
        },
        open: false
    },
    X: { names: {
        },
        open: false
    },
    Y: { names: {
        },
        open: false
    },
    Z: { names: {
        },
        open: false
    },
}